version: '3'

services:
  pinclock:
    build:
      context: .
      dockerfile: Dockerfile
    image: pinclock:latest
    volumes:
      - videos:/build/client/videos
    ports:
      - 3000:3000
  pinclock-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pinclock:latest
    network_mode: "host"
    environment:
      - SOURCE_PATH=${MEDIA_HOME}/pinclock/videos
    env_file:
      - .env
    volumes:
      - videos:/static/videos
      - ${MEDIA_HOME}:${MEDIA_HOME}
      - /etc/wpa_supplicant/wpa_supplicant.conf:/etc/wpa_supplicant/wpa_supplicant.conf
    ports:
      - 3001:3001
    command: node api/server.js

volumes:
  videos: