services:
  pinclock:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: us-docker.pkg.dev/fluid-mix-241702/gcr.io/pinclock:latest
    volumes:
      - videos:/build/client/videos
    ports:
      - 3000:3000
  pinclock-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: us-docker.pkg.dev/fluid-mix-241702/gcr.io/pinclock-api:latest
    environment:
      - SOURCE_PATH=${MEDIA_HOME}/pinclock/videos
    env_file:
      - .env
    volumes:
      - videos:/static/videos
      - ${MEDIA_HOME}:${MEDIA_HOME}
    ports:
      - 3001:3001
    command: node api/server.js

volumes:
  videos: